name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Allows manual triggering from the Actions page

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use Node.js version 18

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          yarn install
          yarn build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Directory to deploy (e.g., Vite build outputs go to 'dist')